feat: improve overall tailwind setup
Powerplex/vite-storybook-poc pull request #5
Opened 2023-01-07 13:39 UTC by acd02

2023-01-07 13:43 UTC, acd02 commented
@Powerplex , FYI, this is why I've updated the scripts ➡️ [customizing colors using css-variables](https://tailwindcss.com/docs/customizing-colors#using-css-variables)

2023-01-07 18:44 UTC, Powerplex commented on package.json
> +    "start": "npm run write-tailwind-conf && npm run write-themes && npm run storybook",
🔥

2023-01-07 18:46 UTC, Powerplex requested changes
I think we should just update the Button styles because it was using the colors that you deleted :)

2023-01-08 16:35 UTC, Powerplex approved these changes

2023-01-08 19:09 UTC, merged